### ISSUE TITLE
Can't set gradient on Spaces with no theme

### ISSUE THREAD

**Issue by GoGagoo** [neurokitti/Arc_Palette#10]
![Uploading IMG_3065.gif…]()

I was able to make a gradient for the 1st space, but when I create a gradient for another space I get this error:

```
1
blank space. could not set!
```

**Comment by Andrew-J-Larson** [comment]
> Uploading IMG_3065.MP4…
> 
> I was able to make a gradient for the 1st space, but when I create a gradient for another space I get this error:
> 
> ```
> 1
> blank space. could not set!
> ```

That's an issue when the space you're trying to set doesn't have a theme set in the first place...

Aka, go back into arc, set a theme for that space, then close out of arc and try the palette app again.

**Comment by GoGagoo** [comment]
> That's an issue when the space you're trying to set doesn't have a theme set in the first place...

Aka, go back into arc, set a theme for that space, then close out of arc and try the palette app again.

it's worked for me, thank you very much!

**Comment by Andrew-J-Larson** [comment]
@GoGagoo You should reopen this issue, I'm going to see what I can do about fixing this so that it can create a space theme from scratch when running into this blank space issue.

**Comment by Dhyfer1** [comment]
> it's worked for me, thank you very much!

You mean it worked in a second space?

**Comment by Andrew-J-Larson** [comment]
> > it's worked for me, thank you very much!
> 
> You mean it worked in a second space?

It's a saying "in the first place", not a typo, didn't mean in the first space.

**Comment by Dhyfer1** [comment]
> It's a saying "in the first place", not a typo, didn't mean in the first space.

Sorry, I still don't understand. Did he mean that he could have applied the palette to a second space?

**Comment by Dhyfer1** [comment]
> It's a saying "in the first place", not a typo, didn't mean in the first space.

Sorry, I still don't understand. Did he mean that he could have applied the palette to a second space?

**Comment by Andrew-J-Larson** [comment]
Let's keep the convo in https://github.com/neurokitti/Arc_Palette/issues/7
