### ISSUE TITLE
Arc API key error (duplicate of #12)

### ISSUE THREAD

**Issue by jacksonb2021** [neurokitti/Arc_Palette#19]
I'm trying to run the main.py file, but keep getting the following error. Running the .bat or .exe closes out immediately, so I had to run it from my IDE to see the errors

```
Traceback (most recent call last):
  File "C:\Users\Jackson.Burns\Downloads\Arc_Palette\main.py", line 263, in <module>
    arc_api = arc_API()
              ^^^^^^^^^
  File "C:\Users\Jackson.Burns\Downloads\Arc_Palette\Arc_API\Arc_API.py", line 39, in __init__
    self.parse_spaces()
  File "C:\Users\Jackson.Burns\Downloads\Arc_Palette\Arc_API\Arc_API.py", line 69, in parse_spaces
    "space_name":i['title'],
                 ~^^^^^^^^^
KeyError: 'title'
```

also, you may not want to close out issues so quickly, because this problem was still being discussed in the first thread

**Comment by Andrew-J-Larson** [comment]
If you check your spaces, does one of them not have a name?

**Comment by valk-ryx** [comment]
You don't need to use the main.py file anymore, you can use the .exe file in the releases tab.

**Comment by Andrew-J-Larson** [comment]
Also, this issue should be moved to https://github.com/neurokitti/Arc_API/issues

**Comment by valk-ryx** [comment]
> Also, this issue should be moved to https://github.com/neurokitti/Arc_API/issues

Hi, sorry that this is off topic, what's your Discord? I want to be able to contact you more easily.

**Comment by Andrew-J-Larson** [comment]
> > Also, this issue should be moved to https://github.com/neurokitti/Arc_API/issues
> 
> Hi, sorry that this is off topic, what's your Discord? I want to be able to contact you more easily.

Messaged you on Discord.

**Comment by jacksonb2021** [comment]
The issue was my default space not having a name. Thanks!

**Comment by Andrew-J-Larson** [comment]
> The issue was my default space not having a name. Thanks!

@jacksonb2021, can you create another space with an empty name?

Then, test run this in an empty folder: https://github.com/Andrew-J-Larson/Arc_Palette/raw/main/resources/Windows/FULL_SETUP_arc_palette.bat

After that gets done running, try the `run_arc_palette.bat` in the same directory.

I want to see if I fixed the bug.

**Comment by Andrew-J-Larson** [comment]
> The issue was my default space not having a name. Thanks!

@jacksonb2021, can you create another space with an empty name?

Then, replace the `Arc_API.py` with this one here: https://github.com/Andrew-J-Larson/Arc_API/raw/main/Arc_API.py

Then, try using the `run_arc_palette.bat` script, I think I fixed the bug, and want to see if it's working.

**Comment by Andrew-J-Larson** [comment]
Disregard, I was able to test and confirm that my fix works.

**Comment by Andrew-J-Larson** [comment]
@jacksonb2021 fix at https://github.com/neurokitti/Arc_Palette/releases/tag/v0.2.1-beta
