### ISSUE TITLE
Exe error (duplicate of #3)

### ISSUE THREAD

**Issue by Mojas84** [neurokitti/Arc_Palette#23]
Hi i download arcpalette.exe but not work https://screenshotx.com/i/bxzjn8

**Comment by Mojas84** [comment]
I can settings HEX colors?

**Comment by Andrew-J-Larson** [comment]
This is related to issue: https://github.com/neurokitti/Arc_Palette/issues/19

**Comment by valk-ryx** [comment]
> I can settings HEX colors?

Unfortunately not at the moment, that will be added in a future update.

**Comment by Andrew-J-Larson** [comment]
This is not an exe error, it's an error with the Arc_API, I need someone experiencing the issue to try out a temporary solution before I push changes to the repo: https://github.com/neurokitti/Arc_Palette/issues/19#issuecomment-2287236356

**Comment by Andrew-J-Larson** [comment]
Disregard, my previous comment.

I have a fix that I'm pushing out shortly, this will be for v1.9

**Comment by Andrew-J-Larson** [comment]
@Mojas84 try the newest release to see if your issue is resolved:
- https://github.com/neurokitti/Arc_Palette/releases/tag/v1.9

**Comment by Mojas84** [comment]
For me still not helping https://screenshotx.com/i/f48m9u

**Comment by Andrew-J-Larson** [comment]
> For me still not helping https://screenshotx.com/i/f48m9u

We haven't created the EXE yet for the update that does fix this issue, hold tight.

Or, use the script method of using the application in the interim.

**Comment by Mojas84** [comment]
Ok thx i wait for fix...

**Comment by Andrew-J-Larson** [comment]
@Mojas84 fixed in https://github.com/neurokitti/Arc_Palette/releases/tag/v0.2.1-beta
