### ISSUE TITLE
windows error (duplicate of #12)

### ISSUE THREAD

**Issue by Bartekpn** [neurokitti/Arc_Palette#27]
![image](https://github.com/user-attachments/assets/a376eeeb-bfc0-4785-b6fc-e1adc641fbd3)

**Comment by valk-ryx** [comment]
Are you using the latest 1.9 version?

**Comment by Andrew-J-Larson** [comment]
@Bartekpn this is fixed now, but don't use the EXE file, that's not been updated.

Use the scripts in https://github.com/neurokitti/Arc_Palette/tree/main/resources/Windows to use the app for now.

**Comment by Andrew-J-Larson** [comment]
@Bartekpn Now we have a new Windows binary, try https://github.com/neurokitti/Arc_Palette/releases/tag/v0.2.0-beta
