### ISSUE TITLE
Is it possible to directly modify arc to dark mode ？

### ISSUE THREAD

**Issue by Eff0rtly** [neurokitti/Arc_Palette#83]
I'm using win10 and the only way I can make the darkness of the arc take effect is by modifying the system to dark mode, but it's well known that win10's dark mode is like shit.

**Comment by Eff0rtly** [comment]
Is it possible to skip the color mode of win10 system and switch the color mode of arc directly?

**Comment by valk-ryx** [comment]
In Arc it has the option to switch between light and dark mode, open the "Edit Theme Colour" menu and it will allow you to flip a switch that has a moon and a sun on it that will allow you to switch between light and dark mode.

**Comment by Eff0rtly** [comment]
In the Windows version of Arc, adjusting the button you mentioned only changes the lightness or darkness of the color you're adjusting, without altering the overall UI mode.

**Comment by Eff0rtly** [comment]
Even after modifying that button, all your menu UI remains white. Only by changing the application mode to dark mode in the Windows system settings can you change the color of the Arc menu.

**Comment by valk-ryx** [comment]
Sorry, do you mean how to change the Arc Palette theme? I misunderstood you as asking how to change Arc's theme.

**Comment by StudioMovieGirl** [comment]
I think the issue is that the Arc API has a bug where it sets the UI mode to dark but only in 1 of the 2 places. i messed around with this and was even able to add more themes allowing you to change things like text color but then school came up. I will see what I can do but I have a lot of school work to finish

**Comment by StudioMovieGirl** [comment]
I fixed the issue with dark and light mode in the Arc API. so i can now add a dark/light mode toggle in Arc pallet!

**Comment by StudioMovieGirl** [comment]
> Even after modifying that button, all your menu UI remains white. Only by changing the application mode to dark mode in the Windows system settings can you change the color of the Arc menu.

still not entirely sure what you want tho

**Comment by Eff0rtly** [comment]
I am not a native English speaker, so sometimes my expressions might not be very clear.
Changes like this.
![image](https://github.com/user-attachments/assets/86c93f40-84ae-48a9-a749-e4e38dcf934e) to 
![image](https://github.com/user-attachments/assets/e7355545-790f-4503-a216-bc6ba43a40a2)

**Comment by Eff0rtly** [comment]
This is what I mean by the overall UI change

**Comment by Eff0rtly** [comment]
What is being adjusted is the dark mode for pop-up menus or context (right-click) menus.

**Comment by Andrew-J-Larson** [comment]
@Eff0rtly those particular submenus are not controllable by the theming engine that Arc uses.

They are controlled by WinUI, outside of the app, so unfortunately, being on Windows 10, you can only control that with the system dark/light mode settings.

**Comment by Andrew-J-Larson** [comment]
I suggest making a bug report with Arc on this, since it appears it's something they forgot to have change alongside with their dark mode theme toggle (they can only set dark or light mode, but can't change the background tint on those submenus, as long as they, Arc, fix their code)

**Comment by Andrew-J-Larson** [comment]
You can report a bug to Arc with the following:
- `Ctrl`+`T` and write "Contact the team"
