### ISSUE TITLE
Spaces not showing up 

### ISSUE THREAD

**Issue by DDDdosg12** [neurokitti/Arc_Palette#85]
I have multiple spaces on my Arc, but the palette just showing 1 space.

![Screenshot 2024-10-14 233524](https://github.com/user-attachments/assets/4219efda-d9e8-4b4a-aab4-24582285bf50)

**Comment by Andrew-J-Larson** [comment]
@DDDdosg12 you're using an older version, you'll need to use the latest version from https://github.com/neurokitti/Arc_Palette/releases/tag/v0.2.4-beta which already has that bug fixed.

**Comment by DDDdosg12** [comment]
Actually I'm using the latest version, sometimes it works but sometimes it doesn't.

**Comment by Andrew-J-Larson** [comment]
> Actually I'm using the latest version, sometimes it works but sometimes it doesn't.

That screenshot is of a version that isn't latest, we've added more button options since that old version.
