### ISSUE TITLE
how to uninstall ArcPallete ?

### ISSUE THREAD

**Issue by Venturi-exe** [neurokitti/Arc_Palette#87]

**Comment by StudioMovieGirl** [comment]
Bruh

**Comment by Venturi-exe** [comment]
It doesn't work for me ;-;
That's why i'm asking how to perform a clean uninstallation 
> Bruh

**Comment by StudioMovieGirl** [comment]
> It doesn't work for me ;-; That's why i'm asking how to perform a clean uninstallation

ngl its just an exe not an installer so its not installed on your system. its just packaged code. so there is no uninstilation if I am not mistaken just deleat the exe
